import { type NextPage } from "next";
import Head from "next/head";

import { trpc } from "../utils/api";

const Home: NextPage = () => {
  const hello = trpc.hello.useQuery({
    text: "what is the weather like today?",
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <p className="text-2xl text-white">
            {hello.data ? hello.data : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
